### ISSUE TITLE
Carp::Always should not clobber the “… at <path> line <line>.\n”

### ISSUE THREAD

**Issue by FGasper** [aferreira/cpan-Carp-Always#8]
```
> perl -MCarp::Always -e 'my $err = "haha at /Where/isit.t line 4545.\n"; die $err;'
haha at -e line 1.
```

```
> perl -e 'my $err = "haha at /Where/isit.t line 4545.\n"; die $err;'
haha at /Where/isit.t line 4545.
```

**Comment by aferreira** [comment]
I am not sure there is a good way to avoid that in the limited setting of `Carp::Always`.

The rationale is that `Carp::Always` is a tiny wrap powered by `Carp::longmess` installed on `$SIG{__WARN__}` and `$SIG{__DIE__}`. When `CORE::warn` and `CORE::die` invoke these signal handlers, they already did the magic of appending the " at FILE line LINE.\n" trail, as in

```
warn "MESSAGE"     =>       warn "MESSAGE at FILE line LINE.\n"
die "MESSAGE"     =>       die "MESSAGE at FILE line LINE.\n"
```
So the clobbering you mentioned is there to avoid duplicates such as
```
MESSAGE at script.pl line 2.
 at script.pl line 2.
```
which happens if I just pass the signal handler arguments to `longmess`.

What `Carp::Always` does is to guess this trail has been put there by `die` / `warn` and that it would be redundant if left intact. This is the most common use case, and works well most of the time.

One proper solution would be to undo *exactly* what was appended to the last argument, and which requires looking at caller stacks to figure out file and line numbers, and then only prune if the trail matches exactly our reconstruction. It defeats the idea to keep `Carp::Always` code simple.

Another idea would be to attempt to control `die` and `warn` with global overrides, which could help accessing the original arguments before the magic trail are generated / appended. In turn, this aggravates the contact surface with other libraries used by the script / application being debugged. It increases unintented interactions for `Carp::Always` and the complexity of the code without corresponding gains.

An ideal solution would be to have some help on the `__DIE__` / `__WARN__` signal handlers to do that deconstruction in a short and efficient way – for example, if instead of appending the trail to the last argument, the trail was pushed as the last argument with some kind of flag to tell it has been put there by the building warn / die mechanism. But, even so, it would be no good for older Perls.

I don' think I see a good solution for that.  Maybe a module like `Devel::Confess` which has a lot more of code is able to a better job in such cases.

**Comment by aferreira** [comment]
I have good news – I think I found a solution at the expense of a (potentially expensive) regex to get rid of duplicate tracebacks (if there are duplicates) – see https://github.com/aferreira/cpan-Carp-Always/blob/master/lib/Carp/Always.pm#L22

I just released a trial version with the fix: https://metacpan.org/release/FERREIRA/Carp-Always-0.15_01

And probably 0.16 release will be out at the end of the day. Thanks for making me look into the issue.

**Comment by FGasper** [comment]
You’re welcome … and thank you very much for taking the time to look into it! :)
